const actionsTypes = {
  GET_ALL_CURRENCIES: ' GET_ALL_CURRENCIES',
  GET_ALL_CURRENCIES_LOADING: ' GET_ALL_CURRENCIES_LOADING',
  GET_ALL_CURRENCIES_ERROR: ' GET_ALL_CURRENCIES_ERROR',
  GET_ALL_CURRENCIES_SUCCESS: ' GET_ALL_CURRENCIES_SUCCESS',
};

export default actionsTypes;
