const actionsTypes = {
  GET_ALL_EVENTS: 'GET_ALL_EVENTS',
  GET_ALL_EVENTS_LOADING: 'GET_ALL_EVENTS_LOADING',
  GET_ALL_EVENTS_ERROR: 'GET_ALL_EVENTS_ERROR',
  GET_ALL_EVENTS_SUCCESS: 'GET_ALL_EVENTS_SUCCESS',
  ADD_EVENTS: 'ADD_EVENTS',
  ADD_EVENTS_LOADING: 'ADD_EVENTS_LOADING',
  ADD_EVENTS_ERROR: 'ADD_EVENTS_ERROR',
  ADD_EVENTS_SUCCESS: 'ADD_EVENTS_SUCCESS',
  GET_QUANTITY_TOTAL: 'GET_QUANTITY_TOTAL',
  GET_QUANTITY_TOTAL_LOADING: 'GET_QUANTITY_TOTAL_LOADING',
  GET_QUANTITY_TOTAL_SUCCESS: 'GET_QUANTITY_TOTAL_SUCCESS',
  GET_QUANTITY_TOTAL_ERROR: 'GET_QUANTITY_TOTAL_ERROR',
};

export default actionsTypes;
