const walletActionsTypes = {
  ADD_NEW_WALLET_SUBMIT: 'ADD_NEW_WALLET_SUBMIT',
  ADD_NEW_WALLET_SUBMIT_LOADING: 'ADD_NEW_WALLET_SUBMIT_LOADING',
  ADD_NEW_WALLET_SUBMIT_SUCCESS: 'ADD_NEW_WALLET_SUBMIT_SUCCESS',
  ADD_NEW_WALLET_SUBMIT_ERROR: 'ADD_NEW_WALLET_SUBMIT_ERROR',
  DELETE_WALLET_SUBMIT: 'DELETE_WALLET_SUBMIT',
  DELETE_WALLET_SUBMIT_LOADING: 'DELETE_WALLET_SUBMIT_LOADING',
  DELETE_WALLET_SUBMIT_SUCESS: 'DELETE_WALLET_SUBMIT_SUCESS',
  DELETE_WALLET_SUBMIT_ERROR: 'DELETE_WALLET_SUBMIT_ERROR',
  GETWALLETS: 'GETWALLETS',
  GETWALLETS_SUCESS: 'GETWALLETS_SUCESS',
  GETWALLETS_ERROR: 'GETWALLETS_ERROR',
  GETWALLETS_LOADING: 'GETWALLETS_LOADING',
  UPDATE_WALLET_SUBMIT: 'UPDATE_WALLET_SUBMIT',
  UPDATE_WALLET_SUCCESS: 'UPDATE_WALLET_SUCCESS',
  UPDATE_WALLET_ERROR: 'UPDATE_WALLET_ERROR',
  UPDATE_WALLET_LOADING: 'UPDATE_WALLET_LOADING',
};

export default walletActionsTypes;
