const actionsTypes = {
  LOGIN_INPUT_SUBMIT: "LOGIN_INPUT_SUBMIT",
  LOGIN_INPUT_SUBMIT_LOADING: "LOGIN_INPUT_SUBMIT_LOADING",
  LOGIN_INPUT_SUBMIT_SUCESS: "LOGIN_INPUT_SUBMIT_SUCESS",
  LOGIN_INPUT_SUBMIT_ERROR: "LOGIN_INPUT_SUBMIT_ERROR",
  SIGNIN_INPUT_SUBMIT: " SIGNIN_INPUT_SUBMIT",
  SIGNIN_INPUT_SUBMIT_LOADING: " SIGNIN_INPUT_SUBMIT_LOADING",
  SIGNIN_INPUT_SUBMIT_ERROR: " SIGNIN_INPUT_SUBMIT_ERROR",
  SIGNIN_INPUT_SUBMIT_SUCESS: " SIGNIN_INPUT_SUBMIT_SUCESS",
  FORGOTPASSWORD_INPUT_SUBMIT: "FORGOTPASSWORD_INPUT_SUBMIT",
  FORGOTPASSWORD_INPUT_SUBMIT_SUCESS: "FORGOTPASSWORD_INPUT_SUBMIT_SUCESS",
  FORGOTPASSWORD_INPUT_SUBMIT_LOADING: "FORGOTPASSWORD_INPUT_SUBMIT_LOADING",
  FORGOTPASSWORD_INPUT_SUBMIT_ERROR: "FORGOTPASSWORD_INPUT_SUBMIT_ERROR",
};

export default actionsTypes;
