const actionsTypes =  {
LOGIN_INPUT_CHANGE : "LOGIN_INPUT_CHANGE",
LOGIN_INPUT_SUBMIT : "LOGIN_INPUT_SUBMIT",
LOGIN_INPUT_SUBMIT_LOADING : 'LOGIN_INPUT_SUBMIT_LOADING',
LOGIN_INPUT_LOGOUT : "LOGIN_INPUT_LOGOUT",
LOGIN_INPUT_LOGOUT_SUCESS : "LOGIN_INPUT_LOGOUT_SUCESS",
LOGIN_INPUT_LOGOUT_ERROR : "LOGIN_INPUT_LOGOUT_ERROR",
LOGIN_INPUT_SUBMIT_SUCESS : "LOGIN_INPUT_SUBMIT_SUCESS",
LOGIN_INPUT_SUBMIT_ERROR : "LOGIN_INPUT_SUBMIT_ERROR",
CHECK_AUTH : "CHECK_AUTH",
CHECK_AUTH_SUCESS : " CHECK_AUTH_SUCESS"
}

export default actionsTypes