const actionsTypes = {
  GET_ALL_PLATFORMS: ' GET_ALL_PLATFORMS',
  GET_ALL_PLATFORMS_LOADING: ' GET_ALL_PLATFORMS_LOADING',
  GET_ALL_PLATFORMS_ERROR: ' GET_ALL_PLATFORMS_ERROR',
  GET_ALL_PLATFORMS_SUCCESS: ' GET_ALL_PLATFORMS_SUCCESS',
};

export default actionsTypes;
